sudo: false

language: node_js

node_js:
  - '6'
  - '8'
  - '10'

branches:
  only:
    - master
    - travis-ci

before_install:
  - pip install --user awscli
  - npm install --no-save --no-package-lock
  - npm install -g istanbul coveralls

after_script:
  - [[ "$TRAVIS_PULL_REQUEST" != "false" ]] && echo not false
  - [[ "$TRAVIS_PULL_REQUEST" = "false" ]] && echo is false
  - echo is pull request $TRAVIS_PULL_REQUEST
  - echo trigger Travis
  - aws s3 sync ./coverage s3://bigeasy/addendum/$TRAVIS_JOB_NUMBER/coverage
