sudo: false

language: node_js

node_js:
  - '6'
  - '8'
  - '10'

branches:
  only:
    - master
    - travis-ci

before_install:
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
  - npm install --no-save --no-package-lock
  - npm install -g istanbul coveralls
