sudo: false

language: node_js

node_js:
  - '6'
  - '8'
  - '10'

branches:
  only:
    - master
    - travis-ci

before_install:
  - pip install --user awscli
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
  - npm install --no-save --no-package-lock
  - npm install -g istanbul coveralls

after_script:
  - echo did I run?
  - s3 sync ./coverage s3://bigeasy/test/coverage
  - artifacts upload --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --bucket bigeasy log/ coverage/
